<ver>0.7</ver>
<efn>C:\Documents and Settings\CGU\\Becky\Final\motor_language.exp</efn>
<con>
<pause>P</pause>
<pause_code></pause_code>
<port1>1</port1>
<quit>Q</quit>
<quit_code></quit_code>
<resume>R</resume>
<resume_code></resume_code>
<send_output>0</send_output>
<start_code></start_code>
</con>
<dbi></dbi>
<dbs>button</dbs>
<ddi>0</ddi>
<dds>
<device>
<color>0</color>
<height>0</height>
<index>0</index>
<name>Primary Display Driver</name>
<refresh>0</refresh>
<width>0</width>
</device>
</dds>
<ddv>Primary Display Driver</ddv>
<dir>C:\Documents and Settings\CGU\\Becky\Final</dir>
<dmd>0</dmd>
<dmh>0</dmh>
<dmr>1</dmr>
<dmw>0</dmw>
<dsd>C:\Documents and Settings\CGU\\Becky\Final\motor pic</dsd>
<dxv>8</dxv>
<fir></fir>
<idt>1000</idt>
<ipi>0</ipi>
<isb>10000</isb>
<lfd>C:\Documents and Settings\CGU\\Becky\Final</lfd>
<lnb>0</lnb>
<lno>0</lno>
<log>
<delimiter>9</delimiter>
<general_list>1</general_list>
<set_def_file></set_def_file>
<stimulus_list>0</stimulus_list>
<subject_id></subject_id>
<subject_id_pol>0</subject_id_pol>
<video_list>0</video_list>
</log>
<lol>1</lol>
<lpr></lpr>
<mss>4</mss>
<nam>motorlanguage</nam>
<ops>
<opp>
<del>0</del>
<pil>0</pil>
<ppa>0x378</ppa>
</opp>
</ops>
<pda>0x378</pda>
<pdb>none</pdb>
<pdd>0</pdd>
<pdi>1</pdi>
<pdr>7</pdr>
<pdv></pdv>
<pia>0x378</pia>
<ppi></ppi>
<rdl>
<device>
<axis>
<max>1000</max>
<min>-1000</min>
<name>X-禸</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>Y-禸</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<axis>
<max>1000</max>
<min>-1000</min>
<name>近</name>
<restricted>1</restricted>
<scale>1</scale>
</axis>
<name>菲公</name>
</device>
</rdl>
<rep>1</rep>
<rts>1</rts>
<sbs>100000</sbs>
<sce>
<idv>
<ibn>秙 0</ibn>
<ibn>秙 1</ibn>
<idn>菲公</idn>
</idv>
<sfn>all_scenarios</sfn>
</sce>
<sce>
<idv>
<ibn>秙 0</ibn>
<ibn>秙 1</ibn>
<idn>菲公</idn>
</idv>
<sfn>C:\Documents and Settings\CGU\\Becky\Final\pic_word_exp.sce</sfn>
</sce>
<sce>
<idv>
<ibn>秙 0</ibn>
<ibn>秙 1</ibn>
<idn>菲公</idn>
</idv>
<sfn>C:\Documents and Settings\CGU\\Becky\Final\letterYN.sce</sfn>
</sce>
<sce>
<idv>
<ibn>秙 0</ibn>
<ibn>秙 1</ibn>
<idn>菲公</idn>
</idv>
<sfn>C:\Documents and Settings\CGU\\Becky\Final\pic_word.pcl</sfn>
</sce>
<sce>
<idv>
<ibn>秙 0</ibn>
<ibn>秙 1</ibn>
<idn>菲公</idn>
</idv>
<sfn>C:\Documents and Settings\CGU\\Becky\Final\YN.pcl</sfn>
</sce>
<sce>
<idv>
<ibn>秙 0</ibn>
<ibn>秙 1</ibn>
<idn>菲公</idn>
</idv>
<sfn>C:\Documents and Settings\CGU\\Becky\Final\motorII.sce</sfn>
</sce>
<sce>
<idv>
<ibn>秙 0</ibn>
<ibn>秙 1</ibn>
<idn>菲公</idn>
</idv>
<sfn>C:\Documents and Settings\CGU\\Becky\Final\practise_pic_word_exp.sce</sfn>
</sce>
<sce>
<idv>
<ibn>秙 0</ibn>
<ibn>秙 1</ibn>
<idn>菲公</idn>
</idv>
<sfn>C:\Documents and Settings\CGU\\Becky\Final\practise_pic_word.pcl</sfn>
</sce>
<sce>
<idv>
<ibn>秙 0</ibn>
<ibn>秙 1</ibn>
<idn>菲公</idn>
</idv>
<sfn>C:\Documents and Settings\CGU\\Becky\Final\practise_letterYN.sce</sfn>
</sce>
<sce>
<idv>
<ibn>秙 0</ibn>
<ibn>秙 1</ibn>
<idn>菲公</idn>
</idv>
<sfn>C:\Documents and Settings\CGU\\Becky\Final\practise_YN.pcl</sfn>
</sce>
<sde>
<custom_buf>sec_hw</custom_buf>
<mixer>dx_software</mixer>
</sde>
<sdv>璶臱笆祘Α</sdv>
<smc>2</smc>
<smd>16</smd>
<smr>44100</smr>
<srd>
<cts>0</cts>
<dsrin>0</dsrin>
<dsrout>0</dsrout>
<dtr>disable</dtr>
<rts>disable</rts>
<spd></spd>
<spn></spn>
<spp></spp>
<spr></spr>
<sps></sps>
</srd>
<srs>1</srs>
<ssb>2000</ssb>
<tpi></tpi>
<udt>0</udt>
<uex>0</uex>
<ufi>0</ufi>
<unc>0</unc>
<upb>1</upb>
<urp>1</urp>
